version: 0.0
os: linux
#files:
#  - source: /src/
#    destination: /var/www/html/
#hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies
#      timeout: 300
#      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
#files:
#  - source: /src/
#    destination: /temp/build
#  - source: Dockerfile
#    destination: /temp/build
hooks:
  BeforeInstall:
    - location: docker_scripts/pull.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: docker_scripts/run.sh
        timeout: 300
        runas: root
  ApplicationStop:
    - location: docker_scripts/stop.sh
      timeout: 300
      runas: root

