version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: docker_scripts/pull.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: docker_scripts/run.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: docker_scripts/stop.sh
      timeout: 300
      runas: root

